### ISSUE TITLE
Composer installation

### ISSUE THREAD

**Issue by Rubenvanhoeyveld** [DBDiff/DBDiff#24]
Hi,

I can't install with Composer.

![image](https://cloud.githubusercontent.com/assets/3180443/17931161/46ad39b2-6a0a-11e6-8e1a-b9167cdd7915.png)

Any idea how I can fix this?

**Comment by jasdeepkhalsa** [comment]
@Rubenvanhoeyveld Try with `composer require "dbdiff/dbdiff:@dev"`

The issue is noted here: https://github.com/composer/composer/issues/5211

**Comment by Rubenvanhoeyveld** [comment]
I'm still having issues following the documentation to make dbdiff work...

I have composer install dbdiff in the Z:\path\to\project\vendor directory.

The documentation says 

>Make sure you are in the root of your application for all the following steps, using 'cd' to navigate on the command line to where you have placed your "dbdiff" folder

>We are going to assume that composer.phar is installed inside your "dbdiff" folder. If it is installed elsewhere you will need to use it's exact path

>1. If you didn't install DBDiff with composer, install the dependencies of the project with: php composer.phar install
>2. Make a .dbdiff file by following the File Examples and place it in the root of your "dbdiff" directory
>3. Type ./dbdiff {dbdiff command here e.g. server1.db1:server1.db2} to start the app! See Command-Line API for more details on which commands you can run.

>You should see something like...

>	ℹ Now calculating schema diff for table `foo`
>	ℹ Now calculating data diff for table `foo`
>	ℹ Now generating UP migration
>	ℹ Now generating DOWN migration
>	ℹ Writing migration file to /path/to/dbdiff/migration.sql
>	✔ Completed

But this happens:

Z:\path\to\project\>./dbdiff
'.' is not recognized as an internal or external command,
operable program or batch file.

I think either I don't understand the documentation, or the instructions aren't very clear...
