### ISSUE TITLE
option to split output into multiple dumps, one for each table

### ISSUE THREAD

**Issue by vesper8** [DBDiff/DBDiff#33]
I would find it helpful and useful if the sql dump output could be automatically separated into multiple dumps, one for each table.

i know you're trying to keep the cli lean but this would just be an additional optional value

**Comment by jhbsk** [comment]
This may be something we consider as a feature in the future

In the meantime though, the way to achieve this would be to run multiple DBDiff commands against each table, along with specifying a specific output name for each table e.g.

```bash
./dbdiff server1.development.table1:server2.production.table1 --output=./output-dir/table-1.sql
./dbdiff server1.development.table2:server2.production.table2 --output=./output-dir/table-2.sql
```
