### ISSUE TITLE
PHP 7.x support

### ISSUE THREAD

**Issue by Rubenvanhoeyveld** [DBDiff/DBDiff#37]
I haven't tested this yet, but I might be needing this tool in several PHP 7.x environments. Will this cause any problems?

**Comment by jhbsk** [comment]
Would be good if you could give this a test run in such an environment and see if any errors popup?

However, the codebase is very simple and built on top of some core Laravel and Symfony components so should be really easy to upgrade to work with PHP 7

**Comment by Rubenvanhoeyveld** [comment]
PHP Fatal error:  Interface 'JsonSerializable' not found in (...)vendor/illuminate/support/Illuminate/Support/Fluent.php on line 8

After some googling, the interface seems to come from the php5-json package... But how do we fix this for php7?

**Comment by vjoao** [comment]
Tested in PHP7. No errors came up.

**Comment by jhbsk** [comment]
I'm also using DBDiff successfully with PHP 7 on Ubuntu 17.04 with no issues.

Closing this ticket for now :)
