### ISSUE TITLE
Template file limitations

### ISSUE THREAD

**Issue by CodingPeak** [DBDiff/DBDiff#38]
I'm trying to output the up and down sql code into a CodeIgniter Migrations file. This is a php file with a class with up and down methods.

It looks like the template file can't be used when there's actual PHP code in it. Is there a way past this? Or what is the exact reason this doesn't work?

Idea: how can we make it work? If we can't, note the limitations in the documentation.

**Comment by jhbsk** [comment]
Hi @CodingPeak,

Please give the idea in #43 a try and let me know if it works. Of course this assumes a similar `execute` command is supported in CodeIgniter which can just execute the raw SQL produced by DBDiff.

I'm closing this ticket for now, but please re-open if you still think there's some limitation here.
