### ISSUE TITLE
append 

### ISSUE THREAD

**Issue by mandevx** [DBDiff/DBDiff#39]
Hi first of all let me start saying your tool looks very promising especially the level of description and details written. Before i jump into installing every thing and trying I have few simple questions and your answer will be highly appreciated .

1. Does it support append as output sql ?
2. Does it support innodb ?

**Comment by jhbsk** [comment]
Hi @mandevx,

Yes, the output is all SQL.
Yes, innodb should be supported (both databases you are comparing should use the same storage engine otherwise this will also be noted in the output SQL diff!)
