### ISSUE TITLE
Readme mentions mysqldbcompare what about mysqldiff

### ISSUE THREAD

**Issue by CMCDragonkai** [DBDiff/DBDiff#40]
Just wondering if DBDiff has considered https://dev.mysql.com/doc/mysql-utilities/1.5/en/mysqldiff.html

**Comment by jhbsk** [comment]
@CMCDragonkai Yep, this was also tested. mysqldbcompare pretty much has the same API as mysqldiff but does more than mysqldiff. However, they both produce diffs that are not satisfactory for any real-world usage.
