### ISSUE TITLE
windows 10 64 bit incompatiable

### ISSUE THREAD

**Issue by danleahy** [DBDiff/DBDiff#42]
Just installed, everything, 

php 5.6.3
composer 1.4.1

I installed the dependencies using composer install

I setup my .dbdiff configuration file

When i tried running it from the command line , i got 
'dbdiff' is not recognized as an internal or external command,
operable program or batch file.

I renamed dbdiff to dbdiff.exe and ran it again and was told the dbdiff is a 16 bit application that is incompatiable with 64 bit windows

![image](https://cloud.githubusercontent.com/assets/3416610/23908102/f9436baa-08ca-11e7-9198-9ccdf5aad741.png)

**Comment by vjoao** [comment]
For anyone coming to this:

This is a PHP script file. You should run it like `php dbdiff <options>`

**Comment by jhbsk** [comment]
@danleahy did @vjoao comment help solve your issue? I'm closing this ticket for now and if you still have problems feel free to open a new issue
