### ISSUE TITLE
SSH tunnel

### ISSUE THREAD

**Issue by Zilus** [DBDiff/DBDiff#56]
I have a vagrant machine (with puphpet)
The only way to connect to MySQL is via ssh tunneling, IS there a way to use dbdiff with this type of connection?

**Comment by isgroup-srl** [comment]
```
ssh -L 3306:localhost:3306 <host>
```
Please note that on the remote MySQL you need an account able to connect from `127.0.0.1` and not `localhost`.

Integrating the feature in DBDiff should not be difficult, it's an execve call to place before connecting.
