### ISSUE TITLE
SSH Tunnel

### ISSUE THREAD

**Issue by ulo23k** [DBDiff/DBDiff#76]
I know this topic have been brought up but i am unable to get it working with ssh tunneling.

./dbdiff --template=templates/simple-db-migrate.tmpl --server1=xxxxxxx:xxxxxxxx@localhost:3335 --server2=xxxxxxxx:xxxxxxx@localhost:3334 server1.xxxxx.xxxxx:server2.xxxxx.xxxxx

This is the result that i get:

✖ Can't connect to target database

**Comment by nullwriter** [comment]
How did u resolve this?

**Comment by ulo23k** [comment]
It was a mistake on my side. I misspelled database name. Once I corrected
it, everything ran accordingly.
